[tool.poetry]
name = "strawberry-mypy-issue-repo-dependency"
version = "0.1.0"
description = ""
authors = ["david"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
